# Project Euler problem 29
# How many unique terms in the sequence generated by a**b,
# for 2<=a<=100, 2<=b<=100?

terms = []
for a in range(2, 101):
    for b in range(2, 101):
        if a**b not in terms:
            terms.append(a**b)

#print(sorted(terms))
print(len(terms))
